Repository ampproject/amp-toolbox-php, pull requests merged in 2020-12, with the labels that each got.

#39 Fix broken spec test for converting intrinsic layout
  resources/local_fallback/rtv/metadata
  tests/Optimizer/SpecTest.php
  tests/spec/transformers/experimental/AddBlurryImagePlaceholders/adds_blurry_placeholders_where_needed/expected_output.html
  tests/spec/transformers/valid/AddBlurryImagePlaceholders/adds_blurry_placeholders_where_needed/expected_output.html
  tests/spec/transformers/valid/AddBlurryImagePlaceholders/adds_blurry_placeholders_where_needed/input.html
  tests/spec/transformers/valid/MinifyHtml/minifies_inline_amp-script/expected_output.html
  tests/spec/transformers/valid/ServerSideRendering/transforms_layout_intrinsic/expected_output.html
  tests/spec/transformers/valid/ServerSideRendering/transforms_layout_intrinsic/input.html
  tests/src/MarkupComparison.php
Labels: Bug, SSR

#42 Raise PHPStan level to 5
  phpstan.neon.dist
  src/Dom/Document.php
  src/Exception/FailedToGetFromRemoteUrl.php
  src/Optimizer/Transformer/PreloadHeroImage.php
  src/RuntimeVersion.php
Labels: Tech Debt

#40 Improve PHPUnit integration
  .github/workflows/test.yml
  composer.json
  src/Optimizer/ImageDimensions.php
  tests/AmpTest.php
  tests/CssLengthTest.php
  tests/DevModeTest.php
  tests/Dom/DocumentTest.php
  tests/Dom/ElementTest.php
  tests/Optimizer/ConfigurationTest.php
  tests/Optimizer/CssRuleTest.php
  tests/Optimizer/CssRulesTest.php
  tests/Optimizer/ErrorCollectionTest.php
  tests/Optimizer/ImageDimensionsTest.php
  tests/Optimizer/SpecTest.php
  tests/Optimizer/TransformationEngineTest.php
  tests/Optimizer/Transformer/AmpBoilerplateTest.php
  tests/Optimizer/Transformer/AmpRuntimeCssTest.php
  tests/Optimizer/Transformer/PreloadHeroImageTest.php
  tests/Optimizer/Transformer/ReorderHeadTest.php
  tests/Optimizer/Transformer/ServerSideRenderingTest.php
  tests/Optimizer/Transformer/TransformedIdentifierTest.php
  tests/RuntimeVersionTest.php
  tests/UrlTest.php
  tests/src/AssertContainsCompatibility.php
  tests/src/TestCase.php
Labels: Testing

#36 Skip escaped slashes when normalizing self-closing tags
  src/Dom/Document.php
  tests/Dom/DocumentTest.php
Labels: Bug, DOM

#38 issue#37: change padding calculation from round to number_format
  src/Optimizer/Transformer/ServerSideRendering.php
Labels: Bug, SSR

#45 Update spec tests - 2020-12-10
  resources/local_fallback/rtv/metadata
  tests/Optimizer/SpecTest.php
  tests/spec/transformers/valid/PreloadHeroImage/amp-img-object-fit-object-position/expected_output.html
  tests/spec/transformers/valid/PreloadHeroImage/amp-img-object-fit-object-position/input.html
  tests/spec/transformers/valid/PreloadHeroImage/attributes/expected_output.html
  tests/spec/transformers/valid/PreloadHeroImage/attributes/input.html
Labels: Testing

#46 Fix @covers annotations
  tests/AmpTest.php
  tests/CssLengthTest.php
  tests/DevModeTest.php
  tests/Dom/DocumentTest.php
  tests/Dom/ElementTest.php
  tests/Optimizer/ConfigurationTest.php
  tests/Optimizer/CssRuleTest.php
  tests/Optimizer/CssRulesTest.php
  tests/Optimizer/ErrorCollectionTest.php
  tests/Optimizer/ImageDimensionsTest.php
  tests/Optimizer/TransformationEngineTest.php
  tests/Optimizer/Transformer/AmpBoilerplateTest.php
  tests/Optimizer/Transformer/AmpRuntimeCssTest.php
  tests/Optimizer/Transformer/PreloadHeroImageTest.php
  tests/Optimizer/Transformer/ReorderHeadTest.php
  tests/Optimizer/Transformer/ServerSideRenderingTest.php
  tests/Optimizer/Transformer/TransformedIdentifierTest.php
  tests/RuntimeVersionTest.php
  tests/UrlTest.php
Labels: Testing

#48 Add .gitattributes file
  .gitattributes
Labels: Distribution

#50 Add code coverage collection
  .github/workflows/test.yml
  phpunit.xml
Labels: Infrastructure, Testing
