Repository ampproject/amp-toolbox-php, pull requests merged in 2020-11, with the labels that each got.

#8 Add change log
  CHANGELOG.md
Labels: Distribution

#21 Rename Extension::IMAGE to Extension::IMG for consistency
  CHANGELOG.md
  src/Extension.php
  src/Optimizer/Transformer/PreloadHeroImage.php
Labels: Tech Debt

#22 Release 0.1.0
  CHANGELOG.md
Labels: Release

#23 Update composer command in docs
  README.md
Labels: Documentation

#30 Use magic $html property in normalizeHtmlAttributes()
  src/Dom/Document.php
Labels: Bug, DOM

#35 Update fallback resources - 2020-11-25
  resources/local_fallback/rtv/metadata
  resources/local_fallback/v0.css
Labels: SSR, dependencies
