Repository ampproject/amp-toolbox-php, pull requests merged in 2021-09, with the labels that each got.

#337 Update documentation for OptimizeHeroImages
  README.md
Labels: Documentation

#356 Add `$headers` argument to `RemoteGetRequest::get()`
  src/RemoteGetRequest.php
  src/RemoteRequest/CurlRemoteGetRequest.php
  src/RemoteRequest/FallbackRemoteGetRequest.php
  src/RemoteRequest/FilesystemRemoteGetRequest.php
  src/RemoteRequest/StubbedRemoteGetRequest.php
  tests/RemoteRequest/FallbackRemoteGetRequestTest.php
Labels: Breaking Change, Optimizer

#357 Refactor CLI option retrieval to improve typing
  src/Cli/Options.php
  tests/Cli/OptionsTest.php
Labels: Tech Debt, CLI
