Repository ampproject/amp-toolbox-php, pull requests merged in 2021-02, with the labels that each got.

#57 Sync latest spec test suite - 2020-02-04
  src/Optimizer/Transformer/ServerSideRendering.php
  tests/Optimizer/SpecTest.php
  tests/spec/transformers/valid/ServerSideRendering/transforms_layout_responsive/expected_output.html
  tests/spec/transformers/valid/ServerSideRendering/transforms_layout_responsive/input.html
Labels: SSR, Testing

#64 Avoid running sync on Composer update
  composer.json
Labels: Distribution, Testing

#54 Secure HTML entities within template text
  src/Dom/Document.php
  tests/Dom/DocumentTest.php
Labels: DOM, Upstream Bug

#49 Support dimensions with units
  resources/local_fallback/rtv/metadata
  src/LengthUnit.php
  src/Optimizer/ImageDimensions.php
  tests/LengthUnitTest.php
  tests/Optimizer/ImageDimensionsTest.php
  tests/spec/transformers/valid/ServerSideRendering/transforms_layout_responsive/expected_output.html
Labels: Bug, SSR

#58 Add GHA workflow to sync test suite and create PR
  .github/workflows/sync-local-fallback-files.yml
  .github/workflows/sync-spec-test-suite.yml
  .github/workflows/test.yml
Labels: Infrastructure

#78 Run tests on all pushes
  .github/workflows/test.yml
Labels: Testing
